version: "3.8"

services:
  db:
    container_name: library-management-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: library_management_db
    ports:
      - "5441:5432"

  redis:
    image: redis
    container_name: library-management-redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - "6380:6379"

volumes:
    redis_volume_data:
